[tools]
node = "24.16.0"
"npm:gulp" = "5"
"npm:semantic-release" = "25.0.3"

prek = "0.4.3"

[tasks.prepare-release]
description = "Add release dependencies"
run = "npm install \"@semantic-release/exec@7.1.0\""
[tasks.release]
description = "Create a Semantic Release"
run = "semantic-release"
